# controller_list:
#   - name: ur_arm_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: True
#     joints:
#       - shoulder_pan_joint
#       - shoulder_lift_joint
#       - elbow_joint
#       - wrist_1_joint
#       - wrist_2_joint
#       - wrist_3_joint
#   - name: gripper_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: True
#     joints:
#       - finger_joint
ur_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint:
      p: 2000
      d: 20
      i: 1
      i_clamp: 1
    shoulder_lift_joint:
      p: 6000
      d: 40
      i: 1
      i_clamp: 1
    elbow_joint:
      p: 2000
      d: 20
      i: 1
      i_clamp: 1
    wrist_1_joint:
      p: 500
      d: 1
      i: 1
      i_clamp: 1
    wrist_2_joint:
      p: 500
      d: 1
      i: 1
      i_clamp: 1
    wrist_3_joint:
      p: 10
      d: 0.1
      i: 0
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - finger_joint
  gains:
    finger_joint:
      p: 10
      d: 0.1
      i: 1
      i_clamp: 1